name: "Build SafaOS's toolchain"

on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Update
      run: rustup default 1.85.1
    - name: build
      run: ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: x86_64-unknown-safaos
        # A file, directory or wildcard pattern that describes what to upload
        path: x86_64-unknown-safaos-toolchain
  build-aarch64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Prepare System
      run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu
    - name: Update
      run: rustup default 1.85.1
    - name: build
      run: ./build.sh -a aarch64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: aarch64-unknown-safaos
        # A file, directory or wildcard pattern that describes what to upload
        path: aarch64-unknown-safaos-toolchain
  release:
    needs: [build-x86, build-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Prepare Release
      run: |
        cd artifacts
        cd x86_64-unknown-safaos && tar -zcvf ../x86_64_toolchain.tar x86_64-unknown-safaos-toolchain/*
        cd ../aarch64-unknown-safaos && tar -zcvf ../aarch64_toolchain.tar aarch64-unknown-safaos-toolchain/*
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "x86_64_toolchain.tar, aarch64_toolchain.tar"
        # set prerelease to true if tag name contains "test"
        prerelease: ${{ contains(github.ref_name, 'test') }}
      # Release only if it's a tag
      if: startsWith(github.ref, 'refs/tags/')