name: "Build SafaOS's toolchain"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: init
      run: ./init.sh
    - name: build
      run: ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: x86_64-unknown-safaos
        # A file, directory or wildcard pattern that describes what to upload
        path: x86_64-unknown-safaos-toolchain

